// <auto-generated />
using System;
using ESG.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ESG.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251216193214_aiservicemigration")]
    partial class aiservicemigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ESG.Api.Models.APPROVAL_STATUS", b =>
                {
                    b.Property<int>("APPROVALSTATUSID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("APPROVALSTATUSID"));

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("APPROVALSTATUSID");

                    b.ToTable("APPROVAL_STATUS");
                });

            modelBuilder.Entity("ESG.Api.Models.CUSTOMER", b =>
                {
                    b.Property<int>("CUSTOMERID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CUSTOMERID"));

                    b.Property<string>("ADDRESS")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<string>("CUSTOMERCODE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DATETIMECREATED")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FIRSTNAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GENDER")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("LASTNAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SECTOR")
                        .HasColumnType("int");

                    b.HasKey("CUSTOMERID");

                    b.ToTable("CUSTOMER");
                });

            modelBuilder.Entity("ESG.Api.Models.ESG_AI_RECOMMENDATION", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("CONFIDENCE")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATETIMECREATED")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LOANAPPLICATIONID")
                        .HasColumnType("int");

                    b.Property<string>("MODELVERSION")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PAYLOAD")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RECOMMENDATION")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<short>("RISKLEVEL")
                        .HasMaxLength(50)
                        .HasColumnType("smallint");

                    b.Property<string>("STAGE")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("ID");

                    b.ToTable("ESG_AI_RECOMMENDATION");
                });

            modelBuilder.Entity("ESG.Api.Models.ESG_CHECKLIST_ASSESSMENT", b =>
                {
                    b.Property<int>("CHECKLISTDETAILID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CHECKLISTDETAILID"));

                    b.Property<int>("CHECKLISTITEMID")
                        .HasColumnType("int");

                    b.Property<string>("COMMENT_")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATETIMECREATED")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LOANAPPLICATIONID")
                        .HasColumnType("int");

                    b.Property<int>("RESPONSETYPEID")
                        .HasColumnType("int");

                    b.Property<int>("SCORE")
                        .HasColumnType("int");

                    b.Property<int>("WEIGHT")
                        .HasColumnType("int");

                    b.HasKey("CHECKLISTDETAILID");

                    b.ToTable("ESG_CHECKLIST_ASSESSMENT");
                });

            modelBuilder.Entity("ESG.Api.Models.ESG_CHECKLIST_ITEM", b =>
                {
                    b.Property<int>("CHECKLISTITEMID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CHECKLISTITEMID"));

                    b.Property<string>("CATEGORY")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CHECKLISTITEM")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("INDICATORTYPE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("ISINUSE")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RESPONSETYPEID")
                        .HasColumnType("int");

                    b.Property<int>("WEIGHT")
                        .HasColumnType("int");

                    b.HasKey("CHECKLISTITEMID");

                    b.ToTable("ESG_CHECKLIST_ITEM");
                });

            modelBuilder.Entity("ESG.Api.Models.ESG_CHECKLIST_ITEM_SCORE", b =>
                {
                    b.Property<int>("SCOREID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SCOREID"));

                    b.Property<int>("CHECKLISTITEMID")
                        .HasColumnType("int");

                    b.Property<int>("RESPONSETYPEID")
                        .HasColumnType("int");

                    b.Property<int>("RESPONSETYPEVALUE")
                        .HasColumnType("int");

                    b.Property<int>("SCORE")
                        .HasColumnType("int");

                    b.HasKey("SCOREID");

                    b.ToTable("ESG_CHECKLIST_ITEM_SCORE");
                });

            modelBuilder.Entity("ESG.Api.Models.ESG_CHECKLIST_RESPONSE", b =>
                {
                    b.Property<int>("RESPONSETYPEID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RESPONSETYPEID"));

                    b.Property<string>("NAME")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RESPONSETYPEID");

                    b.ToTable("ESG_CHECKLIST_RESPONSE");
                });

            modelBuilder.Entity("ESG.Api.Models.ESG_CHECKLIST_SUMMARY", b =>
                {
                    b.Property<int>("SUMMARYID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SUMMARYID"));

                    b.Property<double>("AVGSCORE")
                        .HasColumnType("double");

                    b.Property<string>("COMMENT_")
                        .HasColumnType("longtext");

                    b.Property<int>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATETIMECREATED")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LOANAPPLICATIONID")
                        .HasColumnType("int");

                    b.Property<int>("RATINGID")
                        .HasColumnType("int");

                    b.Property<double>("TOTALSCORE")
                        .HasColumnType("double");

                    b.Property<double>("TOTALWEIGHT")
                        .HasColumnType("double");

                    b.HasKey("SUMMARYID");

                    b.ToTable("ESG_CHECKLIST_SUMMARY");
                });

            modelBuilder.Entity("ESG.Api.Models.LOAN_APPLICATION", b =>
                {
                    b.Property<int>("LOANAPPLICATIONID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LOANAPPLICATIONID"));

                    b.Property<double>("AMOUNT")
                        .HasColumnType("double");

                    b.Property<DateTime>("APPLICATIONDATE")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("APPROVALSTATUSID")
                        .HasColumnType("int");

                    b.Property<int>("CREATEDBY")
                        .HasColumnType("int");

                    b.Property<int>("CURRENCYID")
                        .HasColumnType("int");

                    b.Property<int>("CUSTOMERID")
                        .HasColumnType("int");

                    b.Property<DateTime>("DATETIMECREATED")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("INTERESTRATE")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("LOANPURPOSE")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PRODUCTID")
                        .HasColumnType("int");

                    b.Property<bool?>("SUBMITTEDFORAPPRAISAL")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TENOR")
                        .HasColumnType("int");

                    b.HasKey("LOANAPPLICATIONID");

                    b.ToTable("LOAN_APPLICATION");
                });
#pragma warning restore 612, 618
        }
    }
}
